export enum DriverStatus {
  OFFLINE = 'OFFLINE',

  ONLINE = 'ONLINE',

  ON_ROUTE_TO_PICKUP = 'ON_ROUTE_TO_PICKUP',

  AT_RESTAURANT = 'AT_RESTAURANT',

  ON_ROUTE_TO_DELIVERY = 'ON_ROUTE_TO_DELIVERY',

  AT_CUSTOMER = 'AT_CUSTOMER',

  ORDER_DELIVERED = 'ORDER_DELIVERED',

  BREAK = 'BREAK',
}
