export enum OrderStatus {
  PLACED = 'PLACED',

  ACCEPTED = 'ACCEPTED',

  READY_FOR_PICKUP = 'READY_FOR_PICKUP',

  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',

  DELIVERED = 'DELIVERED',

  CANCELLED = 'CANCELLED',

  FAILED = 'FAILED',
}
